// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTUDesc
{
    public int iJobID { get; set; }

    public string vLogisticsTransportation { get; set; }

    public string vSpecialPackaging { get; set; }

    public string vAuditIncludes { get; set; }

    public string vDataErasure { get; set; }

    public string vReportingSettlement { get; set; }

    public string vPayment { get; set; }

    public string vProductEligibility { get; set; }

    public string vAppleiCloudLock { get; set; }

    public string vProductGradingB { get; set; }

    public string vProductGradingC { get; set; }

    public string vProductGradingD { get; set; }

    public string vRecycling { get; set; }
}