// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userCartDetail
{
    public int iCartDetailID { get; set; }

    public int iCartID { get; set; }

    public int iCategory { get; set; }

    public int iManufacturer { get; set; }

    public int iModelID { get; set; }

    public bool bIsAccessible { get; set; }

    public int iProcessorType { get; set; }

    public int iProcessorGen { get; set; }

    public int iMemory { get; set; }

    public int iHDD { get; set; }

    public string vGrade { get; set; }

    public int iQuantity { get; set; }

    public decimal mPrice { get; set; }

    public bool bDOD { get; set; }

    public decimal mTotal { get; set; }
}