// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_partnerLinkIP
{
    public int iIPPartnerCode { get; set; }

    public string vIP { get; set; }

    public int? iUserIDPartner { get; set; }

    public bool bActive { get; set; }

    public DateTime dCreatedDate { get; set; }

    public DateTime? dInactiveDate { get; set; }
}