// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userEmailCampaignDetail
{
    public int iEmailCampaingDetailID { get; set; }

    public int iEmailCampaingID { get; set; }

    public string vEmailGroup { get; set; }
}