// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userEmail
{
    public int iEmailID { get; set; }

    public string vEmail { get; set; }

    public string vName { get; set; }

    public string vEmailGroup { get; set; }

    public DateTime dCreatedDate { get; set; }

    public DateTime? dUpdatedDate { get; set; }

    public bool bStatus { get; set; }
}