// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userLocation
{
    public int iLogisticID { get; set; }

    public int iUserID { get; set; }

    public virtual Detail_TTU_user iUser { get; set; }

    public string vLocationLabel { get; set; }

    public string vLocationEmail { get; set; }

    public string vLocationContactPerson { get; set; }

    public string vLocationStreetAddress { get; set; }

    public string vSuiteAppt { get; set; }

    public string vCity { get; set; }

    public string vState { get; set; }

    public string vPostalCode { get; set; }

    public bool bIsActive { get; set; }

    public string vIPCreated { get; set; }

    public DateTime dDateCreated { get; set; }
}