// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_user
{
    public int iUserID { get; set; }

    public string vEmail { get; set; }

    public string vPassword { get; set; }

    public string vFirstName { get; set; }

    public string vLastName { get; set; }

    public string vTitle { get; set; }

    public string vCompanyName { get; set; }

    public string vOfficePhone { get; set; }

    public string vExtension { get; set; }

    public string vCellphone { get; set; }

    public bool? bIsAdmin { get; set; }

    public int? iTTUTechPartner { get; set; }

    public bool bActive { get; set; }

    public string vIPCreation { get; set; }

    public DateTime? dDateCreation { get; set; }

    public int? iUserIDPartner { get; set; }
}