// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userManualQuoteLocation
{
    public int iManualQuoteLocID { get; set; }

    public int iManualQuoteID { get; set; }

    public int iLogisticID { get; set; }
}