// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_ModelMaster
{
    public int iModelID { get; set; }

    public string vModelNumber { get; set; }

    public int iCategoryID { get; set; }

    public int iCreatedBy { get; set; }

    public DateTime dDateCreated { get; set; }

    public bool bNotificationSent { get; set; }

    public decimal? yBGradeMarketplaceFMV { get; set; }

    public decimal? yBGradeRetailFMV { get; set; }

    public decimal? yBGradeWholeSaleFMV { get; set; }

    public decimal? yCGradeMarketplaceFMV { get; set; }

    public decimal? yCGradeRetailFMV { get; set; }

    public decimal? yCGradeWholeSaleFMV { get; set; }

    public decimal? yDGradeWholeSaleFMV { get; set; }

    public decimal? nWeight { get; set; }

    public decimal? nLength { get; set; }

    public decimal? nWidth { get; set; }

    public decimal? nHeight { get; set; }

    public bool? bACAdaptorIncluded { get; set; }

    public bool? bKeyboardIncluded { get; set; }

    public bool? bMouseIncluded { get; set; }

    public bool? bTouchScreen { get; set; }

    public bool? bFingerPrintRdr { get; set; }

    public bool? bWebCam { get; set; }

    public bool? bStylus { get; set; }

    public bool? bWIFI { get; set; }

    public int? iMfg { get; set; }

    public int? iUpdatedBy { get; set; }

    public DateTime? dDateUpdated { get; set; }

    public virtual ICollection<Detail_ModelMasterPricing> Detail_ModelMasterPricing { get; set; } = new List<Detail_ModelMasterPricing>();
}