// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userManualQuoteDetail
{
    public int iManualQuoteDetID { get; set; }

    public int iManualQuoteID { get; set; }

    public string vManufacturer { get; set; }

    public string vModelNumber { get; set; }

    public string vHDD { get; set; }

    public string vRam { get; set; }

    public string vProcessor { get; set; }

    public int iQuantity { get; set; }
}