// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userCart
{
    public int iCartID { get; set; }

    public int iUserID { get; set; }

    public int vShippingType { get; set; }

    public bool bSerializedReport { get; set; }

    public int iLogisticID { get; set; }

    public decimal? mTotal { get; set; }

    public decimal? mTotalSerializedReport { get; set; }

    public decimal? mTotalShipping { get; set; }

    public decimal? mTotalDOD { get; set; }

    public decimal? mTotalPayout { get; set; }

    public int? iBoxStatusID { get; set; }

    public DateTime? dDateCreated { get; set; }

    public string vImageName { get; set; }

    public DateTime? bDateSigned { get; set; }

    public int iQuoteNumber { get; set; }
}