// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Detail_TTU_userEmailCampaign
{
    public int iEmailCampaingID { get; set; }

    public int iUserID { get; set; }

    public int iEmailTemplateID { get; set; }

    public string vName { get; set; }

    public string vSubject { get; set; }

    public string vHTMLBody { get; set; }

    public DateTime dDateCreated { get; set; }
}