// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Ref_Main
{
    public int iRefMainID { get; set; }

    public string vReferenceID { get; set; }

    public string vDescription { get; set; }

    public string vTagValue { get; set; }

    public string vTagHelp { get; set; }

    public string vReferenceArea { get; set; }

    public int? iRefOrder { get; set; }

    public string cRefMainActive { get; set; }

    public string vReferenceIDGroup { get; set; }

    public bool? bIsApproved { get; set; }

    public string vApprovedBy { get; set; }

    public DateTime? dApprovedOn { get; set; }

    public string vCulture { get; set; }

    public string vCreatedBy { get; set; }

    public DateTime? dDateCreated { get; set; }

    public string vRef1 { get; set; }

    public string vRef2 { get; set; }
}