// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class Ref_Cat
{
    public int iCatID { get; set; }

    public string vCatDescription { get; set; }

    public string cCatActive { get; set; }

    public string vProductCode { get; set; }

    public string vCategoryType { get; set; }

    public int? nAVGWeight { get; set; }
}