// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class vw_TTU_ManualQuoteList
{
    public int iManualQuoteID { get; set; }

    public int iUserID { get; set; }

    public int vShippingType { get; set; }

    public bool bSerializedReport { get; set; }

    public DateTime dDateCreated { get; set; }

    public string QuoteStatus { get; set; }
}