// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace slTradeIn.Data;

public partial class vw_TTU_BoxList
{
    public int iUserID { get; set; }

    public int iCartID { get; set; }

    public string vLocationLabel { get; set; }

    public string vLocationContactPerson { get; set; }

    public DateTime? dDateCreated { get; set; }

    public string QuoteStatus { get; set; }
}